version: '3.7'

services:
    gui:
        build: ..
        volumes:
            - .:/code
            - data:/data
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
        entrypoint: python dummy.py
    dashboard:
        build: ..
        entrypoint: python -m Dashboard.app
        ports:
            - "8080:80"

volumes:
    data: